---
ID: "4defbb19-ad7b-4ebc-80f8-a504938aa77f"
Parent: "cc9af76c-4fba-44d8-bef2-5fffaa743c16"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Foundation/Rules/_RulesSettings/Rules Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20170318T204336Z
